a = input('Digite algo: ')
print('Otipo primitivo desse valor é: ', type(a))
print('Só tem espaços? ',a.isspace())
print('É um número? ',a.isnumeric())
print('É um alfabético? ',a.isalpha())
print('É um alfanumérico? ',a.isalnum())
print('Está em maiúscula? ',a.isupper())
print('Está em nimúscula? ',a.islower())
print('Está capitalizada? ',a.istitle())